import type { Metadata } from "next";
import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "main layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div
        className={`flex flex-col min-h-svh`}
      >
        <Header />
        {children}
      </div>
    </html>
  );
}
