export const MOCK_SITES = [
  {
    id: 1,
    title: 'Escape Cafe',
    description: 'Go against the grain',
    imageColor: 'bg-zinc-800',
    logoColor: 'bg-white text-black',
    logoLetter: 'E',
    isNew: true,
    isLocked: false,
  },
  {
    id: 2,
    title: 'Humble',
    description: 'AI for smart manufacturing',
    imageColor: 'bg-orange-900/30',
    logoColor: 'bg-orange-500',
    logoLetter: 'H',
    isNew: true,
    isLocked: false,
  },
  {
    id: 3,
    title: 'Mixpanel',
    description: 'Product analytics for mobile, web & more',
    imageColor: 'bg-purple-900/30',
    logoColor: 'bg-purple-600',
    logoLetter: 'M',
    isNew: false,
    isLocked: false,
  },
  {
    id: 4,
    title: 'Claude',
    description: 'AI assistant for life & work',
    imageColor: 'bg-amber-900/30',
    logoColor: 'bg-amber-600',
    logoLetter: 'C',
    isNew: false,
    isLocked: false,
  },
  {
    id: 5,
    title: 'Unified',
    description: 'Centralize your workflow',
    imageColor: 'bg-blue-900/30',
    logoColor: 'bg-blue-500',
    logoLetter: 'U',
    isNew: false,
    isLocked: true,
  },
  {
    id: 6,
    title: 'Approach',
    description: 'Approachable Intelligence',
    imageColor: 'bg-rose-900/30',
    logoColor: 'bg-rose-500',
    logoLetter: 'A',
    isNew: false,
    isLocked: true,
  },
  {
    id: 7,
    title: 'MindMarket',
    description: 'Marketplace for ideas',
    imageColor: 'bg-green-900/30',
    logoColor: 'bg-green-500',
    logoLetter: 'M',
    isNew: false,
    isLocked: true,
  },
  {
    id: 8,
    title: 'Zenith',
    description: 'Reach your peak performance',
    imageColor: 'bg-indigo-900/30',
    logoColor: 'bg-indigo-500',
    logoLetter: 'Z',
    isNew: false,
    isLocked: true,
  },
]
