import type { Metadata } from 'next'
import Header from '@/components/layout/header'

export const metadata: Metadata = {
  title: 'main layout',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='flex min-h-svh flex-col'>
      <Header />
      {children}
    </div>
  )
}
