/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    adminUsers: AdminUserAuthOperations;
  };
  blocks: {};
  collections: {
    'inspiration-websites': InspirationWebsite;
    clients: Client;
    'credit-history': CreditHistory;
    'website-submissions': WebsiteSubmission;
    media: Media;
    categories: Category;
    'website-style': WebsiteStyle;
    adminUsers: AdminUser;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    clients: {
      creditHistory: 'credit-history';
    };
  };
  collectionsSelect: {
    'inspiration-websites': InspirationWebsitesSelect<false> | InspirationWebsitesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'credit-history': CreditHistorySelect<false> | CreditHistorySelect<true>;
    'website-submissions': WebsiteSubmissionsSelect<false> | WebsiteSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'website-style': WebsiteStyleSelect<false> | WebsiteStyleSelect<true>;
    adminUsers: AdminUsersSelect<false> | AdminUsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: AdminUser & {
    collection: 'adminUsers';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Main collection for storing website inspiration entries. Automatically captures screenshots and favicons from provided URLs. Supports categorization, styling tags, and additional media attachments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inspiration-websites".
 */
export interface InspirationWebsite {
  id: string;
  title: string;
  description: string;
  category?: string | null;
  style: string[];
  /**
   * Original website URL (for screenshots)
   */
  pageUrl?: string | null;
  /**
   * Screenshot URL (auto-generated from pageUrl)
   */
  imgUrl?: string | null;
  /**
   * Original favicon URL
   */
  faviconUrl?: string | null;
  /**
   * Favicon URL (auto-generated from faviconUrl)
   */
  favicon?: string | null;
  /**
   * Additional media (video or image)
   */
  additionalMedia?: (string | null) | Media;
  /**
   * Pre-computed gradient color extracted from screenshot
   */
  gradientColor?: string | null;
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload and manage additional media assets (images and videos) for inspiration websites. Media items are automatically linked to InspirationWebsites when pageUrl matches.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * The original website's url
   */
  pageUrl: string;
  /**
   * Type of media (auto-detected from file)
   */
  type?: ('image' | 'video') | null;
  /**
   * Upload image or video directly to Supabase
   */
  mediaUrl?: string | null;
  altText?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage client accounts and their subscription plans. Each client is linked to their credit history.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  /**
   * Supabase user ID (unique identifier)
   */
  userId: string;
  /**
   * User email address (optional, can be provided by user)
   */
  email?: string | null;
  /**
   * User subscription plan
   */
  currentPlan?: ('free' | 'pro' | 'enterprise') | null;
  /**
   * Block this user from using credits and accessing services
   */
  isBlocked?: boolean | null;
  /**
   * Authentication provider used during registration
   */
  provider?: ('n/a' | 'email' | 'google' | 'github') | null;
  /**
   * Whether the user has verified their email address
   */
  isVerified?: boolean | null;
  /**
   * All credit transactions for this user
   */
  creditHistory?: {
    docs?: (string | CreditHistory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Track user credit history including monthly free credits and purchased credits. Credits expire after 1 month.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-history".
 */
export interface CreditHistory {
  id: string;
  client?: (string | null) | Client;
  /**
   * Supabase user ID
   */
  userId: string;
  /**
   * Number of credits (5 for monthly free, variable for purchased)
   */
  creditAmount: number;
  /**
   * Type of credit allocation
   */
  source: 'monthly_free' | 'purchased' | 'signup_bonus';
  updatedAt: string;
  createdAt: string;
}
/**
 * User-submitted website requests for the inspiration gallery. Review and approve submissions to add them to the main collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-submissions".
 */
export interface WebsiteSubmission {
  id: string;
  name?: string | null;
  email?: string | null;
  /**
   * URL of the website being submitted
   */
  websiteUrl: string;
  message?: string | null;
  /**
   * Review status of the submission
   */
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage website categories for organizing inspiration entries. Categories provide taxonomical classification to help filter and group websites by type or purpose.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  category: string;
  value: string;
  order?: number | null;
}
/**
 * Define and manage style tags for inspiration websites. Style tags help categorize websites by visual design patterns, aesthetics, or UI/UX approaches (e.g., minimalist, glassmorphism, dark mode).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-style".
 */
export interface WebsiteStyle {
  id: string;
  style: string;
  value: string;
  order?: number | null;
}
/**
 * Manage admin panel users and their access permissions. Configure user roles (admin, moderator, guest) to control who can create, edit, and delete content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminUsers".
 */
export interface AdminUser {
  id: string;
  name?: string | null;
  phone?: string | null;
  isBlocked?: boolean | null;
  roles?: ('admin' | 'moderator' | 'guest')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'inspiration-websites';
        value: string | InspirationWebsite;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'credit-history';
        value: string | CreditHistory;
      } | null)
    | ({
        relationTo: 'website-submissions';
        value: string | WebsiteSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'website-style';
        value: string | WebsiteStyle;
      } | null)
    | ({
        relationTo: 'adminUsers';
        value: string | AdminUser;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: string | PayloadKv;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'adminUsers';
    value: string | AdminUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'adminUsers';
    value: string | AdminUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inspiration-websites_select".
 */
export interface InspirationWebsitesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  style?: T;
  pageUrl?: T;
  imgUrl?: T;
  faviconUrl?: T;
  favicon?: T;
  additionalMedia?: T;
  gradientColor?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  userId?: T;
  email?: T;
  currentPlan?: T;
  isBlocked?: T;
  provider?: T;
  isVerified?: T;
  creditHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-history_select".
 */
export interface CreditHistorySelect<T extends boolean = true> {
  client?: T;
  userId?: T;
  creditAmount?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-submissions_select".
 */
export interface WebsiteSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  websiteUrl?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  pageUrl?: T;
  type?: T;
  mediaUrl?: T;
  altText?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  category?: T;
  value?: T;
  order?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-style_select".
 */
export interface WebsiteStyleSelect<T extends boolean = true> {
  style?: T;
  value?: T;
  order?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminUsers_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  isBlocked?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}